# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb20a20fe61e387cc64299d4480b4354a48e2208f0e518f2552ab66fd2721395b128d167b0dfab22bcf21ae2ec16856063bb478fb39669d60e233c21ee0722bf
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUDNAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_APIKEY"] %> 
  cloudinary_api_secret: <%= ENV["CLOUDINARY_APISECRET"] %> 
  rubypress_host: <%= ENV["RUBYPRESS_HOST"] %>
  rubypress_username: <%= ENV["RUBYPRESS_USERNAME"] %>
  rubypress_password: <%= ENV["RUBYPRESS_PASSWORD"] %>

test:
  secret_key_base: 8c050deb1ea81c3f88fdd086ef204579827f479a75e8cb858c7bf0a192cc6bd8c535d900067b6394b22506ab6216676b44176c44c92bea499a77378da5f8a02b
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUDNAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_APIKEY"] %> 
  cloudinary_api_secret: <%= ENV["CLOUDINARY_APISECRET"] %> 
  rubypress_host: <%= ENV["RUBYPRESS_HOST"] %>
  rubypress_username: <%= ENV["RUBYPRESS_USERNAME"] %>
  rubypress_password: <%= ENV["RUBYPRESS_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUDNAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_APIKEY"] %> 
  cloudinary_api_secret: <%= ENV["CLOUDINARY_APISECRET"] %> 
  rubypress_host: <%= ENV["RUBYPRESS_HOST"] %>
  rubypress_username: <%= ENV["RUBYPRESS_USERNAME"] %>
  rubypress_password: <%= ENV["RUBYPRESS_PASSWORD"] %>
